#!/usr/bin/env python3
"""Phase 2: extract and cross-check every identifier in the thesis.

Collects, with file and line:
  - citation commands and keys (natbib, biblatex and plain \\cite forms)
  - bibliography entry keys, including duplicates within and across .bib files
  - labels, including those generated by figure-like macros found by
    discover_project.py (e.g. \\myfig whose 4th argument becomes fig:#4)
  - internal references (\\ref, \\eqref, \\cref, \\Cref, \\autoref, ...)
  - graphics, including those inserted through such macros
  - hard-coded object numbers in prose ("Figure 3", "Section 4.2")

and reports undefined and unused identifiers, duplicates and missing
graphics. These are facts, not judgments: whether a hard-coded number
refers to this thesis or to another paper is left to review.

Usage:
    collect_identifiers.py DISCOVERY_JSON [--out identifiers.json]
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

from latex_common import MacroTemplate, blank_definitions, reading_position, templates_from_discovery, clean_source, line_of, load_json, read_args, write_json

CITE_RE = re.compile(
    r"\\(?P<cmd>(?:[Pp]arencite|[Tt]extcite|[Aa]utocite|[Ff]ootcite|[Ss]martcite|[Ss]upercite|"
    r"[Cc]ite(?:t|p|alp|alt|author|year|yearpar|title|date|url|num)?|nocite|fullcite|footfullcite)"
    r"s?)\*?(?![A-Za-z])"
)
REF_RE = re.compile(
    r"\\(?P<cmd>ref|eqref|pageref|autoref|nameref|vref|Vref|cref|Cref|crefrange|Crefrange|cpageref|Cpageref|labelcref|namecref|nameCref|zcref|subref)\*?(?![A-Za-z])"
)
LABEL_RE = re.compile(r"\\label\s*\{([^{}]*)\}")
GRAPHICS_RE = re.compile(r"\\includegraphics\s*(?:\[[^\]]*\])?\s*\{([^{}]*)\}")
GRAPHICSPATH_RE = re.compile(r"\\graphicspath\s*\{((?:\{[^{}]*\}\s*)+)\}")
BIB_ENTRY_RE = re.compile(r"@(\w+)\s*[{(]\s*([^,\s]+)\s*,")
HARDCODED_RE = re.compile(
    r"\b(Figure|Fig\.|Figs\.|Table|Tab\.|Section|Sec\.|Chapter|Ch\.|Equation|Eq\.|Eqs\.|"
    r"Appendix|Algorithm|Alg\.|Listing|Theorem|Lemma|Definition)\s*~?\s*"
    r"(\(?\d+(?:\.\d+)*\)?|[A-Z](?![a-z]))"
)
GRAPHIC_EXTS = ("", ".pdf", ".png", ".jpg", ".jpeg", ".eps")


def _section_at(sections: list[tuple[int, str]], line: int) -> str | None:
    current = None
    for start, title in sections:
        if start <= line:
            current = title
        else:
            break
    return current


def scan_file(path: Path, rel_path: str, order: int, templates: dict[str, MacroTemplate]) -> dict:
    text = blank_definitions(clean_source(path.read_text(encoding="utf-8", errors="replace")))
    out: dict[str, list] = {"citations": [], "labels": [], "references": [], "graphics": [], "hardcoded": [], "graphicspaths": []}

    for m in CITE_RE.finditer(text):
        cmd = m.group("cmd")
        i = m.end()
        # Up to two optional arguments (pre/postnote), then the key group.
        # \\cites can take several (pre)(post){keys} groups.
        groups = []
        while True:
            parsed = read_args(text, i, "oom")
            if parsed is None:
                break
            args, end = parsed
            groups.append(args)
            i = end
            # Only the multicite forms (\\cites, \\parencites, ...) take
            # several key groups in a row.
            if not cmd.endswith("s") or text[i:i + 1] not in ("{", "["):
                break
        for args in groups:
            keys = [k.strip() for k in (args[2] or "").split(",") if k.strip()]
            out["citations"].append(
                {
                    "command": cmd,
                    "keys": keys,
                    "prenote": args[0] if args[1] is not None else None,
                    "postnote": args[1] if args[1] is not None else args[0],
                    "file": rel_path,
                    "line": line_of(text, m.start()),
                    "order": order,
                }
            )

    for m in LABEL_RE.finditer(text):
        out["labels"].append({"key": m.group(1).strip(), "file": rel_path, "line": line_of(text, m.start()), "via": "\\label", "order": order})

    for m in REF_RE.finditer(text):
        spec = "mm" if m.group("cmd").lower().endswith("range") else "m"
        parsed = read_args(text, m.end(), spec)
        if parsed is None:
            continue
        keys = []
        for arg in parsed[0]:
            keys += [k.strip() for k in (arg or "").split(",") if k.strip()]
        line_start = text.rfind("\n", 0, m.start()) + 1
        out["references"].append(
            {
                "command": m.group("cmd"),
                "keys": keys,
                "file": rel_path,
                "line": line_of(text, m.start()),
                "order": order,
                "sentence_start": _at_sentence_start(text, m.start(), line_start),
            }
        )

    for m in GRAPHICS_RE.finditer(text):
        if "#" in m.group(1):
            continue  # a macro definition body, handled through the template
        out["graphics"].append({"path": m.group(1).strip(), "file": rel_path, "line": line_of(text, m.start()), "via": "\\includegraphics"})

    for m in GRAPHICSPATH_RE.finditer(text):
        out["graphicspaths"] += re.findall(r"\{([^{}]*)\}", m.group(1))

    for name, template in templates.items():
        for m in re.finditer(r"\\" + re.escape(name) + r"(?![A-Za-z@])", text):
            parsed = read_args(text, m.end(), template.spec)
            if parsed is None:
                continue
            args, _ = parsed
            line = line_of(text, m.start())
            for lt in template.label_templates:
                key = template.expand(lt, args)
                if key:
                    out["labels"].append({"key": key, "file": rel_path, "line": line, "via": "\\" + name, "order": order})
            for gt in template.graphics_templates:
                gpath = template.expand(gt, args)
                if gpath:
                    out["graphics"].append({"path": gpath, "file": rel_path, "line": line, "via": "\\" + name})

    for m in HARDCODED_RE.finditer(text):
        # Skip numbers inside math and cases followed by a citation, which
        # usually point into another paper ("Figure 3 of \citet{x}").
        tail = text[m.end(): m.end() + 40]
        external = bool(re.match(r"\s*(of|in|from)\s+\\(cite|citet|citep|textcite|parencite)", tail)) or bool(
            re.match(r"\s*\\(cite|citep|parencite)", tail)
        )
        out["hardcoded"].append(
            {
                "text": m.group(0),
                "file": rel_path,
                "line": line_of(text, m.start()),
                "likely_external": external,
                "context": text[max(0, m.start() - 60): m.end() + 60].replace("\n", " "),
            }
        )
    return out


def _at_sentence_start(text: str, index: int, line_start: int) -> bool:
    """True if the command opens a sentence: it follows sentence-final
    punctuation, a paragraph break, or \\item, ignoring an opening brace
    or tie. Used to check \\Cref versus \\cref capitalisation."""
    before = text[:index]
    stripped = before.rstrip(" \t~{")
    if not stripped.strip():
        return True
    if re.search(r"\n[ \t]*\n[ \t~{]*$", before):
        return True
    return stripped.endswith((".", "!", "?", "\\item"))


def parse_bib(path: Path, rel_path: str) -> list[dict]:
    text = path.read_text(encoding="utf-8", errors="replace")
    entries = []
    for m in BIB_ENTRY_RE.finditer(text):
        kind = m.group(1).lower()
        if kind in ("string", "comment", "preamble"):
            continue
        entries.append({"key": m.group(2).strip(), "type": kind, "file": rel_path, "line": line_of(text, m.start())})
    return entries


def graphic_exists(project_root: Path, root_dir: Path, including_dir: Path, path: str, graphicspaths: list[str]) -> bool:
    bases = [root_dir, including_dir] + [root_dir / g for g in graphicspaths] + [including_dir / g for g in graphicspaths]
    for base in bases:
        for ext in GRAPHIC_EXTS:
            if (base / (path + ext)).is_file():
                return True
    return False


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("discovery", help="output of discover_project.py")
    parser.add_argument("--out", help="write JSON here instead of stdout")
    args = parser.parse_args()

    discovery = load_json(args.discovery)
    root = Path(discovery["project_root"])
    root_dir = (root / discovery["root_document"]).parent
    templates = templates_from_discovery(discovery)

    citations, labels, references, graphics, hardcoded, graphicspaths = [], [], [], [], [], []
    seen_files = set()
    for order, entry in enumerate(discovery["reading_order"]):
        if entry["file"] in seen_files:
            continue  # a file included twice is scanned once; the duplicate is reported by discovery
        seen_files.add(entry["file"])
        scanned = scan_file(root / entry["file"], entry["file"], order, templates)
        citations += scanned["citations"]
        labels += scanned["labels"]
        references += scanned["references"]
        graphics += scanned["graphics"]
        hardcoded += scanned["hardcoded"]
        graphicspaths += scanned["graphicspaths"]

    bib_entries = []
    for resource in discovery.get("bibliography", {}).get("resources", []):
        candidate = root_dir / resource["resource"]
        if not candidate.is_file():
            candidate = root / resource["resource"]
        if candidate.is_file():
            bib_entries += parse_bib(candidate, str(candidate.resolve().relative_to(root.resolve())))
    if not bib_entries:
        for bib in discovery.get("bib_files", []):
            bib_entries += parse_bib(root / bib, bib)

    # Cross-checks.
    bib_by_key: dict[str, list[dict]] = {}
    for e in bib_entries:
        bib_by_key.setdefault(e["key"], []).append(e)
    label_by_key: dict[str, list[dict]] = {}
    for lab in labels:
        label_by_key.setdefault(lab["key"], []).append(lab)

    cited_keys = {k for c in citations for k in c["keys"]}
    nocite_all = any(c["command"] == "nocite" and "*" in c["keys"] for c in citations)
    referenced_keys = {k for r in references for k in r["keys"]}

    undefined_citations = [
        {**c, "key": k} for c in citations for k in c["keys"] if k != "*" and k not in bib_by_key
    ]
    lower_map: dict[str, list[str]] = {}
    for key in bib_by_key:
        lower_map.setdefault(key.lower(), []).append(key)
    case_mismatches = [
        {**u, "close_match": lower_map[u["key"].lower()]} for u in undefined_citations if u["key"].lower() in lower_map
    ]
    undefined_references = [{**r, "key": k} for r in references for k in r["keys"] if k not in label_by_key]

    position = reading_position(discovery)
    label_pos = {k: min(position(v["file"], v["line"]) for v in vs) for k, vs in label_by_key.items()}
    for r in references:
        here = position(r["file"], r["line"])
        r["forward"] = [k for k in r["keys"] if k in label_pos and label_pos[k] > here]

    missing_graphics = []
    for g in graphics:
        including_dir = (root / g["file"]).parent
        if not graphic_exists(root, root_dir, including_dir, g["path"], graphicspaths):
            missing_graphics.append(g)

    result = {
        "counts": {
            "citation_commands": len(citations),
            "distinct_cited_keys": len(cited_keys - {"*"}),
            "bib_entries": len(bib_entries),
            "labels": len(labels),
            "references": len(references),
            "graphics": len(graphics),
        },
        "citations": citations,
        "bib_entries": bib_entries,
        "labels": labels,
        "references": references,
        "graphics": graphics,
        "undefined_citations": undefined_citations,
        "citation_case_mismatches": case_mismatches,
        "duplicate_bib_keys": [{"key": k, "entries": v} for k, v in bib_by_key.items() if len(v) > 1],
        "unused_bib_entries": [] if nocite_all else [v[0] for k, v in bib_by_key.items() if k not in cited_keys],
        "undefined_references": undefined_references,
        "duplicate_labels": [{"key": k, "labels": v} for k, v in label_by_key.items() if len(v) > 1],
        "empty_or_suspicious_labels": [l for l in labels if not l["key"] or re.search(r"\s", l["key"])],
        "unreferenced_labels": [v[0] for k, v in label_by_key.items() if k not in referenced_keys],
        "missing_graphics": missing_graphics,
        "hardcoded_numbers": hardcoded,
    }
    write_json(result, args.out)


if __name__ == "__main__":
    main()
